verbose: false
language: system

updater:
  strategy: native
  allow-upgrade-now: true
  filename: ${originName}
  proxy:
    uri: ~
    username: ~
    password: ~
  repository:
    check-mode: 1
    check-list:
      - DEFAULT_MODE_IS_BLACKLIST